apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME
spec:
  selector:
    matchLabels:
      app: $IMAGE_NAME
  template:
    metadata:
      labels:
        app: $IMAGE_NAME
    spec:
      containers:
        - name: $IMAGE_NAME
          image: $COMPANY_NAME/$IMAGE_NAME
          command: ["node", "app/index.js"]
          env:
            - name: BOT_TOKEN
              value: $BOT_TOKEN
            - name: BOT_ENDPOINT
              value: $BOT_ENDPOINT
            - name: TEST_RAILS_HOST
              value: $TEST_RAILS_HOST
            - name: TEST_RAILS_USER
              value: $TEST_RAILS_USER
            - name: TEST_RAILS_PASS
              value: $TEST_RAILS_PASS
